version: '3.9'

services:
  web:
    build: .
    container_name: webchatbot-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - .:/www/webchatbot
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn webchatbot.wsgi:application --bind 0.0.0.0:8000"

  redis:
    image: redis:7
    container_name: webchatbot-redis
    restart: unless-stopped

  celery:
    build: .
    container_name: webchatbot-celery
    command: celery -A webchatbot worker --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/www/webchatbot
