version: '3.9'

services:
  web:
    build: .
    container_name: webchatbot-web
    volumes:
      - .:/www/webchatbot
      - static_volume:/www/webchatbot/staticfiles
      - media_volume:/www/webchatbot/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: webchatbot-redis
    restart: unless-stopped

  celery:
    build: .
    container_name: webchatbot-celery
    command: celery -A webChatBot worker --loglevel=info
    volumes:
      - .:/www/webchatbot
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: webchatbot-nginx
    ports:
      - "80:80"
      - "443:443"       # expose HTTPS port as well
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/www/webchatbot/staticfiles:ro
      - media_volume:/www/webchatbot/media:ro
      - /etc/letsencrypt/live/botsdk.rayonweb.com:/etc/letsencrypt/live/botsdk.rayonweb.com:ro
      - /etc/letsencrypt/archive/botsdk.rayonweb.com:/etc/letsencrypt/archive/botsdk.rayonweb.com:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
