# Generated by Django 5.2.1 on 2025-05-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trial_end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_started_at',
        ),
    ]
