# Generated by Django 5.2.1 on 2025-05-13 09:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website_url', models.URLField(unique=True)),
                ('api_key', models.CharField(max_length=150, unique=True)),
                ('sdk', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(choices=[('Arial, sans-serif', 'Arial'), ("'Helvetica Neue', sans-serif", 'Helvetica Neue'), ("'Times New Roman', serif", 'Times New Roman'), ("'Courier New', monospace", 'Courier New'), ("'Georgia', serif", 'Georgia'), ("'Tahoma', sans-serif", 'Tahoma'), ("'Verdana', sans-serif", 'Verdana')], default='Arial, sans-serif', max_length=100)),
                ('border_radius', models.PositiveSmallIntegerField(default=16, help_text='Chat Bot border radius in pixels (between 0 and 25)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('welcome_message', models.CharField(default='Hi there! How can I help you?', max_length=255)),
                ('input_placeholder_text', models.CharField(default='Type your message...', max_length=255)),
                ('scrollbar_width', models.PositiveSmallIntegerField(default=6, help_text='Scrollbar width in pixels (between 4 and 12)', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('chat_icon_bg_color', models.CharField(default='#4a6cf7', max_length=7)),
                ('chat_icon_color', models.CharField(default='#ffffff', max_length=7)),
                ('chat_close_btn_color', models.CharField(default='#ffffff', max_length=7)),
                ('header_bg_color', models.CharField(default='#0d0a0a', max_length=7)),
                ('header_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('msg_box_bg_color', models.CharField(default='#ffbac6', max_length=7)),
                ('scrollbar_color', models.CharField(default='#ffbac6', max_length=7)),
                ('send_btn_color', models.CharField(default='#000000', max_length=7)),
                ('user_message_bg_color', models.CharField(default='#171b2b', max_length=7)),
                ('user_message_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('bot_message_bg_color', models.CharField(default='#573b40', max_length=7)),
                ('bot_message_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('input_container_bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('input_color', models.CharField(default='#000000', max_length=7)),
                ('input_border_color', models.CharField(default='#b9b4b4', max_length=7)),
                ('input_placeholder_color', models.CharField(default='#808080', max_length=7)),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='chatbots.chatbot')),
            ],
        ),
    ]
