# Generated by Django 5.2.1 on 2025-05-12 08:29

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
                ('api_key', models.CharField(max_length=150, unique=True)),
                ('sdk', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorfield.fields.ColorField(default='#2563EB', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#F43F5E', image_field=None, max_length=25, samples=None)),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('button_text', models.CharField(default='Chat with us!', max_length=30)),
                ('welcome_message', models.CharField(default='Hi there! How can I help you?', max_length=255)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100)),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='chatbots.chatbot')),
            ],
        ),
    ]
