# Generated by Django 5.2.1 on 2025-05-12 08:33

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotcustomization',
            old_name='background_color',
            new_name='bg_color',
        ),
        migrations.RenameField(
            model_name='chatbotcustomization',
            old_name='secondary_color',
            new_name='bot_message_bg_color',
        ),
        migrations.RenameField(
            model_name='chatbotcustomization',
            old_name='primary_color',
            new_name='button_bg_color',
        ),
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='button_text',
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='bot_message_color',
            field=colorfield.fields.ColorField(default='#F43F5E', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='#2563EB', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='user_message_bg_color',
            field=colorfield.fields.ColorField(default='#2563EB', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='user_message_color',
            field=colorfield.fields.ColorField(default='#2563EB', image_field=None, max_length=25, samples=None),
        ),
    ]
