# Generated by Django 5.2.1 on 2025-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='input_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='input_container_bg_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='msg_box_bg_color',
            field=models.CharField(default='#1C1718', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='scrollbar_color',
            field=models.CharField(default='#4F4F4F', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='send_btn_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
