# Generated by Django 5.2.1 on 2025-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='api_key',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='sdk',
            field=models.CharField(max_length=150),
        ),
    ]
