# Generated by Django 5.2.1 on 2025-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_chatbot_status_chatbot_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], max_length=20),
        ),
    ]
