# Generated by Django 5.2.1 on 2025-05-12 08:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_rename_background_color_chatbotcustomization_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotcustomization',
            name='border_radius',
            field=models.PositiveSmallIntegerField(default=16, help_text='In pixels'),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='button_hover_bg_color',
            field=colorfield.fields.ColorField(default='#1D4ED8', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='button_hover_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='chat_icon',
            field=models.ImageField(blank=True, null=True, upload_to='chat_icons/'),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='chatbox_position',
            field=models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='button_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
