# Generated by Django 5.2.1 on 2025-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_alter_chatbotcustomization_input_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='messages',
            field=models.PositiveBigIntegerField(default=0, help_text='Total number of messages exchanged between the user and the chatbot.'),
        ),
    ]
