# Generated by Django 5.2.1 on 2025-05-12 10:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_chatbotcustomization_border_radius_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotcustomization',
            old_name='bot_message_color',
            new_name='bot_message_text_color',
        ),
        migrations.RenameField(
            model_name='chatbotcustomization',
            old_name='button_bg_color',
            new_name='header_bg_color',
        ),
        migrations.RenameField(
            model_name='chatbotcustomization',
            old_name='user_message_color',
            new_name='header_text_color',
        ),
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='button_hover_bg_color',
        ),
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='button_hover_text_color',
        ),
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='button_text_color',
        ),
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='chatbox_position',
        ),
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='text_color',
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='btn_color',
            field=colorfield.fields.ColorField(default='#F43F5E', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='msg_box_bg_color',
            field=colorfield.fields.ColorField(default='#F43F5E', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='user_message_text_color',
            field=colorfield.fields.ColorField(default='#2563EB', image_field=None, max_length=25, samples=None),
        ),
    ]
