# Generated by Django 5.2.1 on 2025-05-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0003_alter_chatbot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='website_url',
            field=models.URLField(help_text='Example: https://yourdomain.com — Enter the exact website URL.', unique=True),
        ),
    ]
