# Generated by Django 5.2.1 on 2025-05-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_rename_bot_message_color_chatbotcustomization_bot_message_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='website_url',
            field=models.URLField(unique=True),
        ),
    ]
