# Generated by Django 5.2.1 on 2025-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_alter_chatbot_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
