# Generated by Django 5.2.1 on 2025-05-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0005_alter_chatbot_name_alter_chatbot_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='font_family',
            field=models.CharField(choices=[('Arial, sans-serif', 'Arial'), ("'Helvetica Neue', sans-serif", 'Helvetica Neue'), ("'Times New Roman', serif", 'Times New Roman'), ("'Courier New', monospace", 'Courier New'), ("'Georgia', serif", 'Georgia'), ("'Tahoma', sans-serif", 'Tahoma'), ("'Verdana', sans-serif", 'Verdana')], default='Arial, sans-serif', max_length=100),
        ),
    ]
