# Generated by Django 5.2.1 on 2025-05-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0005_alter_chatbot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='website_url',
            field=models.URLField(help_text='Example: https://yourdomain.com — Enter the exact website URL.'),
        ),
    ]
