# Generated by Django 5.2.1 on 2025-05-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0006_alter_chatbotcustomization_font_family'),
        ('subscriptions', '0005_remove_paymenttransaction_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usersubscription'),
            preserve_default=False,
        ),
    ]
