# Generated by Django 5.2.1 on 2025-05-13 05:32

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0007_chatbot_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='btn_color',
        ),
        migrations.RemoveField(
            model_name='chatbotcustomization',
            name='chat_icon',
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='chat_close_btn_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='chat_icon_bg_color',
            field=colorfield.fields.ColorField(default='#4a6cf7', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='chat_icon_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='input_border_color',
            field=colorfield.fields.ColorField(default='#b9b4b4', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='input_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='input_container_bg_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='input_placeholder_color',
            field=colorfield.fields.ColorField(default='#808080', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='input_placeholder_text',
            field=models.CharField(default='Type your message...', max_length=255),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='scrollbar_color',
            field=colorfield.fields.ColorField(default='#ffbac6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='scrollbar_width',
            field=models.PositiveSmallIntegerField(default=6, help_text='Scrollbar width in pixels (between 4 and 12)', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='chatbotcustomization',
            name='send_btn_color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='bot_message_bg_color',
            field=colorfield.fields.ColorField(default='#573b40', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='bot_message_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='header_bg_color',
            field=colorfield.fields.ColorField(default='#0d0a0a', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='header_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='msg_box_bg_color',
            field=colorfield.fields.ColorField(default='#ffbac6', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='user_message_bg_color',
            field=colorfield.fields.ColorField(default='#171b2b', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='user_message_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
    ]
