# Generated by Django 5.2.1 on 2025-05-13 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0008_remove_chatbotcustomization_btn_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='border_radius',
            field=models.PositiveSmallIntegerField(default=16, help_text='Chat Bot border radius in pixels (between 0 and 25)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
