# Generated by Django 5.2.1 on 2025-05-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0009_alter_chatbotcustomization_border_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='bot_message_bg_color',
            field=models.CharField(default='#573b40', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='bot_message_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='chat_close_btn_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='chat_icon_bg_color',
            field=models.CharField(default='#4a6cf7', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='chat_icon_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='header_bg_color',
            field=models.CharField(default='#0d0a0a', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='header_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='input_border_color',
            field=models.CharField(default='#b9b4b4', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='input_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='input_container_bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='input_placeholder_color',
            field=models.CharField(default='#808080', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='msg_box_bg_color',
            field=models.CharField(default='#ffbac6', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='scrollbar_color',
            field=models.CharField(default='#ffbac6', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='send_btn_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='user_message_bg_color',
            field=models.CharField(default='#171b2b', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='user_message_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
