# Generated by Django 5.2.1 on 2025-05-13 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0010_alter_chatbotcustomization_bot_message_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='border_radius',
            field=models.IntegerField(default=16, help_text='Chat Bot border radius in pixels (between 0 and 25)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='chatbotcustomization',
            name='scrollbar_width',
            field=models.IntegerField(default=6, help_text='Scrollbar width in pixels (between 4 and 12)', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
