# Generated by Django 5.2.1 on 2025-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
