# Generated by Django 5.2.1 on 2025-05-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='plan',
            new_name='subscription',
        ),
    ]
