# Generated by Django 5.2.1 on 2025-05-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_plan_usersubscription_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='subscription',
            new_name='user_subscription',
        ),
    ]
