# Generated by Django 5.2.1 on 2025-05-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_membershipplan_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='duration_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='max_chatbots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
