# Generated by Django 5.2.1 on 2025-05-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_rename_subscription_paymenttransaction_user_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='trial_used',
        ),
    ]
