# Generated by Django 5.2.1 on 2025-05-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_usersubscription_chatbot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='chatbot',
        ),
    ]
